### PR TITLE
Fix issue with targets.thisRobot that caused Glass Hammer to target kernel instead of itself

### LINKED ISSUE #1695: Glass Hammer ("When your kernel takes damage, destroy this robot ...") destroys the kernel, not the robot!

### PR DESCRIPTION
**Pull request by AlexNisnevich**
fix #1695

### CODE REVIEW

File: src/common/vocabulary/targets.ts [hunk 1]
```diff
@@ -247,11 +253,15 @@ export default function targets(state: w.GameState, currentObject: w.Object | nu
     // Prioritize currentObject,
     // but also allow falling back to the currently salient object, if any.
     thisRobot: (): w.ObjectCollection => {
+      // console.log(currentObject);
```
Comment (jacobnisnevich) [inline src/common/vocabulary/targets.ts:256]: Nit: remove all these?

**Review by jacobnisnevich — APPROVED** [review]
