### PR TITLE
Display message for unsupported browsers (fix #1278)

### LINKED ISSUE #1278: Fail gracefully on outdated browsers (maybe too-small-screens too?)

### PR DESCRIPTION
**Pull request by AlexNisnevich**
[ fix #1278 ]

image

### CODE REVIEW

File: src/common/components/NavMenu.tsx [hunk 1]
```diff
@@ -40,6 +40,9 @@ class NavMenu extends React.Component<NavMenuProps & WithStyles> {
     collapsed: {
       width: SIDEBAR_COLLAPSED_WIDTH
     },
+    unsupportedBrowser: {
+      top: 54 + 50
```
Comment (jacobnisnevich) [inline src/common/components/NavMenu.tsx:44]: What are these numbers?

**Review by jacobnisnevich — APPROVED** [review]
