### PR TITLE
Fix various issues arising from 10/29/22 playtest

### LINKED ISSUE #1685: Inactive players *shouldn't* see alerts for command execution errors (only the active player trying to play the card / etc, should)

### LINKED ISSUE #1686: swapPositions() does not actually work reliably (sometimes leading to bizarre situations like objects disappearing or multiple objects in one hex)

### LINKED ISSUE #1687: Clicking on enemy kernel can be blocked by volume bar on smaller screens

### LINKED ISSUE #1688: Exit Sandbox crashes the game

### LINKED ISSUE #1689: "Your robots have Haste" as a passive ability doesn't actually take effect because the afterPlayed trigger gets executed too early

### PR DESCRIPTION
**Pull request by AlexNisnevich**
- fix #1685 
- fix #1686 
- fix #1687 
- fix #1688 
- fix #1689

### CODE REVIEW

File: src/common/util/game.ts [hunk 1]
```diff
@@ -651,8 +651,9 @@ export function updateOrDeleteObjectAtHex(
   cause: w.Cause | null = null,
   shouldApplyAbilities = true
 ): w.GameState {
-  if (!allObjectsOnBoard(state)[hex]) {
-    // Object no longer exists - perhaps it has already been deleted by a previous effect in a chain of triggers?
+  if (!(allObjectsOnBoard(state)[hex]?.id === object.id)) {
```
Comment (jacobnisnevich) [inline src/common/util/game.ts:654]: Can you just do `!==`?

**Review by jacobnisnevich — APPROVED** [review]
