### PR TITLE
Fix issues relating to closing chat and discard pile

### LINKED ISSUE #516: Unable to hide chat
Chat does not hide when you click the two right arrow button.

### PR DESCRIPTION
**Pull request by AlexNisnevich**
Fix #516 and #517.

### CODE REVIEW

File: src/common/components/game/PlayerArea.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ export default class PlayerArea extends Component {
 
   handleSelectCard = (idx) => this.props.gameProps.onSelectCard(idx, this.color);
   handleOpenDiscardPile = () => this.setState({ discardOpen: true });
-  handleCloseDiscardPile = () => this.setState({ discardOpen: true });
```
Comment (jacobnisnevich) [inline src/common/components/game/PlayerArea.js]: Huh. How did this happen?

File: src/common/containers/GameArea.js [hunk 2]
```diff
@@ -291,19 +277,33 @@ export class GameArea extends Component {
...
+  attackPiece = (hexId, intermediateMoveHexId) => {
     if (intermediateMoveHexId) {
       this.props.onMoveRobotAndAttack(this.props.selectedTile, intermediateMoveHexId, hexId);
     } else {
       this.props.onAttackRobot(this.props.selectedTile, hexId);
     }
   }
 
-  placePiece(hexId) {
+  placePiece = (hexId) => {
```
Comment (jacobnisnevich) [inline src/common/containers/GameArea.js]: Is this how we're writing functions now?

Comment (AlexNisnevich) [reply src/common/containers/GameArea.js]: Yes, because only the arrow syntax preserves `this` correctly. That's what caused the bug.

File: src/common/components/game/PlayerArea.js (hunk 1 above)
Comment (AlexNisnevich) [reply src/common/components/game/PlayerArea.js]: I was stupid 😢
