### PR TITLE
Many UX improvements and fixes around the Lobby, websocket connections, etc

### LINKED ISSUE #1646: Automatically disconnect users when they leave the Play page

### LINKED ISSUE #1647: Update "players online" when a user leaves the lobby

### LINKED ISSUE #1648: Stale chat state would persist after leaving and rejoining the lobby

### LINKED ISSUE #1649: Logged-in users joining the lobby no longer trigger a "joined the lobby" message

### LINKED ISSUE #1650: Matchmaking Mode tooltips overlap each other when logged out

### LINKED ISSUE #1651: Track in-lobby players separately from in-game players in the Lobby status display

### PR DESCRIPTION
**Pull request by AlexNisnevich**
fix #1646, fix #1647, fix #1648, fix #1649, fix #1650, fix #1651

### CODE REVIEW

File: src/common/components/play/LobbyStatus.tsx [hunk 1]
```diff
@@ -8,79 +9,82 @@ interface LobbyStatusProps {
...
+                  :{' '}
+                  </b>
+                  {
+                    this.uniquePlayersInLobby
+                      .map((clientId) =>
+                        <div key={clientId} style={{ display: 'inline-block' }}>
+                          {this.renderPlayerName(userDataByClientId[clientId], clientId)}
+                        </div>
+                      )
+                      // https://stackoverflow.com/a/35840806
```
Comment (jacobnisnevich) [inline src/common/components/play/LobbyStatus.tsx:81]: I think this code is pretty readable? Don't think we need this link

**Review by jacobnisnevich — APPROVED** [review]
